# Generated by Django 3.0.3 on 2020-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
