# Generated by Django 3.0.3 on 2020-03-20 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20200319_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='markslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField(blank=True, max_length=3, null=True)),
                ('hin', models.IntegerField(blank=True, max_length=3, null=True)),
                ('eng', models.IntegerField(blank=True, max_length=3, null=True)),
                ('sci', models.IntegerField(blank=True, max_length=3, null=True)),
                ('soc', models.IntegerField(blank=True, max_length=3, null=True)),
                ('mat', models.IntegerField(blank=True, max_length=3, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='practice.sample')),
            ],
        ),
    ]
